### ISSUE TITLE
Exception Value: __new__() got an unexpected keyword argument 'description'

### ISSUE THREAD

**Issue by Alexerson** [core-api/python-client#117]
When upgrading to 2.2.x, I got the following error:
`Exception Value: __new__() got an unexpected keyword argument 'description'`
in 
`File "lib/python3.5/site-packages/django_filters/rest_framework/backends.py:104" in get_schema_fields
`
Downgrading to 2.1.1 fix this. If this is the wanted behaviour, we might need to fix `django_filters`.

**Comment by tomchristie** [comment]
Thanks for the report @Alexerson - yup my screw up here. I've now pushed an updated version that still accepts these now-deprecated arguments, so you should be able to upgrade now.

Some work also to do on updating the openapi codec to accept both forms.

**Comment by rpkilby** [comment]
@tomchristie - I'm assuming that these attributes have been moved to the `Schema` class in `coreschema`?

**Comment by tomchristie** [comment]
Yes they're moving there, although the latest release of the client now supports both styles for the moment.

The schema will allow us to more fully describe the fields on the link. In particular the typing information that it supports is compatible with `jsonschema`, which means we'll be able to fully represent that information in eg. API documentation tooling.

**Comment by tomchristie** [comment]
Latest release resolves this issues - apologies for the churn!
